### ISSUE TITLE
Column doesn't exist.

### ISSUE THREAD

**Issue by Itzmeamario** [josx/ra-data-feathers#89] opened 2019-01-18 22:17 UTC
When using the current version I get (column messages.$sort[id] does not exist), but if I use the code at https://github.com/josx/ra-data-feathers/blob/master/test/restClient.spec.js it works correctly.

If more information is required I'll happily send it.

**Comment by lijoantony** [comment] 2019-01-23 12:56
I am facing a similar issue but for the filters.
I think my issue is caused by a single line change in the new version, which changed the behavior of query filters.

<         Object.assign(query, params.filter)
---
>         Object.assign(query, fetchUtils.flattenObject(params.filter));

**Comment by lijoantony** [comment] 2019-01-23 13:01
Duplicate of #84 ?

**Comment by josx** [comment] 2019-01-29 14:55
Yes I need to do a new release to match master changes. I will do it ASAP

**Closed** 2019-02-12 12:23 UTC
